kind: Service
apiVersion: v1
metadata:
  name: petbook-frontend
  namespace: petbook
  labels:
    app: petbook-frontend
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: petbook-frontend
  type: ClusterIP
  sessionAffinity: None
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: petbook-frontend
  namespace: petbook
  labels:
    app: petbook-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petbook-frontend
      version: v1
  template:
    metadata:
      labels:
        app: petbook-frontend
        version: v1
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            defaultMode: 420
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/petbook-frontend:latest
          name: petbook-frontend
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
